# name of the workflow - in this case, continuous integration
name: ci
# controls when the action will run.  Triggers on all push or pull requests on all branches
on:
  push:
    branches:
    - "*"  # run for branches
  pull_request:
    branches:
    - "*"  # run for branches
#global environment variables used for the jobs below
env:
  REGISTRY_NAME: mmdemotest
  CLUSTER_NAME: demoMMTest
  CLUSTER_RESOURCE_GROUP: mm-demo-front-end-test
  NAMESPACE: sock-shop
  APP_NAME: front-end
  SECRET: deploySecret
  
jobs:
# this job is labeled build - builds docker image and pushes to the registry - likeness to a 'stage'
  build-docker-image:
    # image this operation will run on
    runs-on: ubuntu-latest
    # steps that are executed within the specified stage
    steps:
    # out of the box actions from microsoft
    - uses: actions/checkout@main
    
    # Connect to Azure Container registry (ACR)
    # out of the box actions from microsoft - 'uses' indicates this
    - uses: azure/docker-login@v1
      with:
        # pass in the following variables into the action
        login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }} 
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    # Container build and push to a Azure Container registry (ACR)
    # run a shell script - ie. command line
    - run: |
        docker build . -t ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}
        docker push ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}
        
  prep-for-kubernetes-deployment:
    # add job dependency on 'build'
    needs: build-docker-image
    runs-on: ubuntu-latest
    steps:
    # Create namespace if doesn't exist
    # run a shell script - ie. command line
    - run: |
        echo 'this is where we are going to create namespaces for deployment'
    - run: |
        echo 'this is where we configure the deployment secret'
        
  kubernetes-deployment:
    needs: prep-for-kubernetes-deployment
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo 'this is where we deploy our application to the kubernetes cluster'
        
